-- Catalog tables only contain seed data (regenerated by prisma/seed.ts).
-- inmuebles is still empty at this point, so no real data is lost here.
-- usuarios is untouched by this migration.
TRUNCATE TABLE "estado_inmueble", "tipo_inmueble" CASCADE;

-- DropForeignKey
ALTER TABLE "inmuebles" DROP CONSTRAINT "inmuebles_estadoId_fkey";

-- DropForeignKey
ALTER TABLE "inmuebles" DROP CONSTRAINT "inmuebles_tipoInmuebleId_fkey";

-- AlterTable
ALTER TABLE "estado_inmueble" DROP CONSTRAINT "estado_inmueble_pkey",
ADD COLUMN     "deletedAt" TIMESTAMP(3),
ALTER COLUMN "id" DROP DEFAULT,
ALTER COLUMN "id" SET DATA TYPE TEXT,
ADD CONSTRAINT "estado_inmueble_pkey" PRIMARY KEY ("id");
DROP SEQUENCE "estado_inmueble_id_seq";

-- AlterTable
ALTER TABLE "inmuebles" ALTER COLUMN "tipoInmuebleId" SET DATA TYPE TEXT,
ALTER COLUMN "estadoId" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "tipo_inmueble" DROP CONSTRAINT "tipo_inmueble_pkey",
ADD COLUMN     "deletedAt" TIMESTAMP(3),
ALTER COLUMN "id" DROP DEFAULT,
ALTER COLUMN "id" SET DATA TYPE TEXT,
ADD CONSTRAINT "tipo_inmueble_pkey" PRIMARY KEY ("id");
DROP SEQUENCE "tipo_inmueble_id_seq";

-- AddForeignKey
ALTER TABLE "inmuebles" ADD CONSTRAINT "inmuebles_tipoInmuebleId_fkey" FOREIGN KEY ("tipoInmuebleId") REFERENCES "tipo_inmueble"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "inmuebles" ADD CONSTRAINT "inmuebles_estadoId_fkey" FOREIGN KEY ("estadoId") REFERENCES "estado_inmueble"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
